#!/bin/bash

# StackPilot - Cloudflare Setup
# Configures Cloudflare API access (locally).
# Enables automatic DNS record management.
# Author: Paweł (Lazy Engineer)

set -e

CONFIG_DIR="$HOME/.config/cloudflare"
CONFIG_FILE="$CONFIG_DIR/config"

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  ☁️  Cloudflare DNS Setup                                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will configure Cloudflare API access."
echo "You will be able to automatically add DNS records for your applications."
echo ""

# 1. Check if already configured
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  Found existing configuration: $CONFIG_FILE"
    read -p "Overwrite? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[TtYy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

# 2. Open browser with instructions
echo "📋 Opening Cloudflare page to create a token..."
echo ""
echo "   In the browser:"
echo "   1. Click 'Create Token'"
echo "   2. Click 'Create Custom Token' (at the bottom)"
echo "   3. Add permissions:"
echo "      • Zone → DNS → Edit           (required - DNS records)"
echo "      • Zone → Zone Settings → Edit (optional - SSL, compression)"
echo "      • Zone → Cache Rules → Edit   (optional - Next.js cache)"
echo "   4. In 'Zone Resources' select 'All zones' or specific domains"
echo "   5. Click 'Continue to summary' → 'Create Token'"
echo "   6. Copy the token (shown only once!)"
echo ""
echo "   💡 Zone Settings and Cache Rules permissions are needed for"
echo "      automatic optimization (SSL Flexible, Brotli, cache)."
echo ""

# Open browser (different commands for different systems)
URL="https://dash.cloudflare.com/profile/api-tokens"
if command -v open &> /dev/null; then
    open "$URL"  # macOS
elif command -v xdg-open &> /dev/null; then
    xdg-open "$URL"  # Linux
elif command -v start &> /dev/null; then
    start "$URL"  # Windows (Git Bash)
else
    echo "   Open manually: $URL"
fi

read -p "Press Enter when you've copied the token..."

echo ""
read -s -p "🔑 Paste API Token: " API_TOKEN
echo ""

if [ -z "$API_TOKEN" ]; then
    echo "❌ Token cannot be empty!"
    exit 1
fi

# 3. Verify token
echo ""
echo "Verifying token..."

VERIFY_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json")

if echo "$VERIFY_RESPONSE" | grep -q '"success":true'; then
    echo "✅ Token works!"
else
    echo "❌ Token is invalid or lacks permissions!"
    echo "   Response: $VERIFY_RESPONSE"
    exit 1
fi

# 4. Fetch Zone IDs
echo ""
echo "Fetching domain list..."

ZONES_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json")

# Parse domains — extract (id, name) pairs from result[] array
# jq is preferred, fallback to grep with per-object parsing
ZONE_PAIRS=""
if command -v jq &>/dev/null; then
    ZONE_PAIRS=$(echo "$ZONES_RESPONSE" | jq -r '.result[] | "\(.name)=\(.id)"' 2>/dev/null)
else
    # Fallback: extract objects from result array and parse id+name per object
    # Each zone object has "id" and "name" at the beginning — take them as pairs
    ZONE_PAIRS=$(echo "$ZONES_RESPONSE" \
        | tr '{' '\n' \
        | grep '"name"' \
        | while IFS= read -r obj; do
            local_id=$(echo "$obj" | grep -o '"id":"[^"]*"' | head -1 | sed 's/"id":"//;s/"//')
            local_name=$(echo "$obj" | grep -o '"name":"[^"]*"' | head -1 | sed 's/"name":"//;s/"//')
            # Filter: real domain must have a dot, no spaces
            if [ -n "$local_id" ] && [ -n "$local_name" ] && [[ "$local_name" == *.* ]] && [[ "$local_name" != *" "* ]]; then
                echo "${local_name}=${local_id}"
            fi
        done)
fi

if [ -z "$ZONE_PAIRS" ]; then
    echo "❌ No domains found!"
    echo "   Make sure the token has access to at least one domain."
    exit 1
fi

echo ""
echo "Found domains:"
echo "$ZONE_PAIRS" | cut -d= -f1 | nl
echo ""

# 5. Save configuration
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

cat > "$CONFIG_FILE" << EOF
# Cloudflare API Configuration
# Generated by StackPilot

API_TOKEN=$API_TOKEN

# Zone mappings (domain=zone_id)
EOF

# Save domain=zone_id pairs
echo "$ZONE_PAIRS" >> "$CONFIG_FILE"

chmod 600 "$CONFIG_FILE"

echo ""
echo "✅ Configuration saved: $CONFIG_FILE"
echo ""
echo "🚀 Now you can use:"
echo "   ./local/dns-add.sh subdomain.yourdomain.com SERVER_IP"
echo ""
echo "   Example:"
echo "   ./local/dns-add.sh status.mycompany.com 185.181.10.50"
echo ""
