#!/bin/bash

# StackPilot - Cloudflare Setup
# Configures Cloudflare API access (locally).
# Enables automatic DNS record management.
# Author: Paweł (Lazy Engineer)

set -e

_CF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_CF_DIR/../lib/i18n.sh"
RED="${RED:-\033[0;31m}"
GREEN="${GREEN:-\033[0;32m}"
YELLOW="${YELLOW:-\033[1;33m}"
BLUE="${BLUE:-\033[0;34m}"
NC="${NC:-\033[0m}"

CONFIG_DIR="$HOME/.config/cloudflare"
CONFIG_FILE="$CONFIG_DIR/config"

echo ""
msg "$MSG_CF_HEADER_TOP"
msg "$MSG_CF_HEADER_TITLE"
msg "$MSG_CF_HEADER_BOT"
echo ""
msg "$MSG_CF_INTRO"
msg "$MSG_CF_INTRO2"
echo ""

# 1. Check if already configured
if [ -f "$CONFIG_FILE" ]; then
    msg "$MSG_CF_EXISTING" "$CONFIG_FILE"
    read -p "$(msg_n "$MSG_CF_OVERWRITE")" -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[TtYy]$ ]]; then
        msg "$MSG_CF_CANCELLED"
        exit 0
    fi
fi

# 2. Open browser with instructions
msg "$MSG_CF_OPENING"
echo ""
msg "$MSG_CF_BROWSER_STEP1"
msg "$MSG_CF_BROWSER_STEP2"
msg "$MSG_CF_BROWSER_STEP3"
msg "$MSG_CF_BROWSER_STEP4"
msg "$MSG_CF_BROWSER_STEP5"
msg "$MSG_CF_BROWSER_STEP6"
msg "$MSG_CF_BROWSER_STEP7"
msg "$MSG_CF_BROWSER_STEP8"
msg "$MSG_CF_BROWSER_STEP9"
msg "$MSG_CF_BROWSER_STEP10"
echo ""
msg "$MSG_CF_BROWSER_TIP"
msg "$MSG_CF_BROWSER_TIP2"
echo ""

# Open browser (different commands for different systems)
URL="https://dash.cloudflare.com/profile/api-tokens"
if command -v open &> /dev/null; then
    open "$URL"  # macOS
elif command -v xdg-open &> /dev/null; then
    xdg-open "$URL"  # Linux
elif command -v start &> /dev/null; then
    start "$URL"  # Windows (Git Bash)
else
    msg "$MSG_CF_MANUAL_OPEN" "$URL"
fi

read -p "$(msg_n "$MSG_CF_PRESS_ENTER")"

echo ""
read -s -p "$(msg_n "$MSG_CF_PASTE_TOKEN")" API_TOKEN
echo ""

if [ -z "$API_TOKEN" ]; then
    msg "$MSG_CF_TOKEN_EMPTY"
    exit 1
fi

# 3. Verify token
echo ""
msg "$MSG_CF_VERIFYING"

VERIFY_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json")

if echo "$VERIFY_RESPONSE" | grep -q '"success":true'; then
    msg "$MSG_CF_TOKEN_OK"
else
    msg "$MSG_CF_TOKEN_FAIL"
    msg "$MSG_CF_TOKEN_RESP" "$VERIFY_RESPONSE"
    exit 1
fi

# 4. Fetch Zone IDs
echo ""
msg "$MSG_CF_FETCHING"

ZONES_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json")

# Parse domains — extract (id, name) pairs from result[] array
# jq is preferred, fallback to grep with per-object parsing
ZONE_PAIRS=""
if command -v jq &>/dev/null; then
    ZONE_PAIRS=$(echo "$ZONES_RESPONSE" | jq -r '.result[] | "\(.name)=\(.id)"' 2>/dev/null)
else
    # Fallback: extract objects from result array and parse id+name per object
    # Each zone object has "id" and "name" at the beginning — take them as pairs
    ZONE_PAIRS=$(echo "$ZONES_RESPONSE" \
        | tr '{' '\n' \
        | grep '"name"' \
        | while IFS= read -r obj; do
            local_id=$(echo "$obj" | grep -o '"id":"[^"]*"' | head -1 | sed 's/"id":"//;s/"//')
            local_name=$(echo "$obj" | grep -o '"name":"[^"]*"' | head -1 | sed 's/"name":"//;s/"//')
            # Filter: real domain must have a dot, no spaces
            if [ -n "$local_id" ] && [ -n "$local_name" ] && [[ "$local_name" == *.* ]] && [[ "$local_name" != *" "* ]]; then
                echo "${local_name}=${local_id}"
            fi
        done)
fi

if [ -z "$ZONE_PAIRS" ]; then
    msg "$MSG_CF_NO_DOMAINS"
    msg "$MSG_CF_NO_DOMAINS_HINT"
    exit 1
fi

echo ""
msg "$MSG_CF_FOUND_DOMAINS"
echo "$ZONE_PAIRS" | cut -d= -f1 | nl
echo ""

# 5. Save configuration
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

cat > "$CONFIG_FILE" << EOF
# Cloudflare API Configuration
# Generated by StackPilot

API_TOKEN=$API_TOKEN

# Zone mappings (domain=zone_id)
EOF

# Save domain=zone_id pairs
echo "$ZONE_PAIRS" >> "$CONFIG_FILE"

chmod 600 "$CONFIG_FILE"

echo ""
msg "$MSG_CF_SAVED" "$CONFIG_FILE"
echo ""
msg "$MSG_CF_NOW_USE"
msg "$MSG_CF_NOW_CMD"
echo ""
msg "$MSG_CF_EXAMPLE"
msg "$MSG_CF_EXAMPLE_CMD"
echo ""
