#!/bin/bash

# StackPilot - Cloudflare Setup
# Configures Cloudflare API access (locally).
# Enables automatic DNS record management.
# Author: Paweł (Lazy Engineer)

set -e

CONFIG_DIR="$HOME/.config/cloudflare"
CONFIG_FILE="$CONFIG_DIR/config"

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  ☁️  Cloudflare DNS Setup                                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will configure Cloudflare API access."
echo "You will be able to automatically add DNS records for your applications."
echo ""

# 1. Check if already configured
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  Found existing configuration: $CONFIG_FILE"
    read -p "Overwrite? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[TtYy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

# 2. Open browser with instructions
echo "📋 Opening Cloudflare page to create a token..."
echo ""
echo "   In the browser:"
echo "   1. Click 'Create Token'"
echo "   2. Click 'Create Custom Token' (at the bottom)"
echo "   3. Add permissions:"
echo "      • Zone → DNS → Edit           (required - DNS records)"
echo "      • Zone → Zone Settings → Edit (optional - SSL, compression)"
echo "      • Zone → Cache Rules → Edit   (optional - Next.js cache)"
echo "   4. In 'Zone Resources' select 'All zones' or specific domains"
echo "   5. Click 'Continue to summary' → 'Create Token'"
echo "   6. Copy the token (shown only once!)"
echo ""
echo "   💡 Zone Settings and Cache Rules permissions are needed for"
echo "      automatic optimization (SSL Flexible, Brotli, cache)."
echo ""

# Open browser (different commands for different systems)
URL="https://dash.cloudflare.com/profile/api-tokens"
if command -v open &> /dev/null; then
    open "$URL"  # macOS
elif command -v xdg-open &> /dev/null; then
    xdg-open "$URL"  # Linux
elif command -v start &> /dev/null; then
    start "$URL"  # Windows (Git Bash)
else
    echo "   Open manually: $URL"
fi

read -p "Press Enter when you've copied the token..."

echo ""
read -s -p "🔑 Paste API Token: " API_TOKEN
echo ""

if [ -z "$API_TOKEN" ]; then
    echo "❌ Token cannot be empty!"
    exit 1
fi

# 3. Verify token
echo ""
echo "Verifying token..."

VERIFY_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json")

if echo "$VERIFY_RESPONSE" | grep -q '"success":true'; then
    echo "✅ Token works!"
else
    echo "❌ Token is invalid or lacks permissions!"
    echo "   Response: $VERIFY_RESPONSE"
    exit 1
fi

# 4. Fetch Zone IDs
echo ""
echo "Fetching domain list..."

ZONES_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json")

# Parse domains
ZONES=$(echo "$ZONES_RESPONSE" | grep -o '"name":"[^"]*"' | sed 's/"name":"//g' | sed 's/"//g')
ZONE_IDS=$(echo "$ZONES_RESPONSE" | grep -o '"id":"[^"]*"' | head -20 | sed 's/"id":"//g' | sed 's/"//g')

if [ -z "$ZONES" ]; then
    echo "❌ No domains found!"
    echo "   Make sure the token has access to at least one domain."
    exit 1
fi

echo ""
echo "Found domains:"
echo "$ZONES" | nl
echo ""

# 5. Save configuration
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

cat > "$CONFIG_FILE" << EOF
# Cloudflare API Configuration
# Generated by StackPilot

API_TOKEN=$API_TOKEN

# Zone mappings (domain=zone_id)
EOF

# Add domain to zone ID mapping
ZONE_ARRAY=($ZONE_IDS)
i=0
echo "$ZONES" | while read -r domain; do
    echo "${domain}=${ZONE_ARRAY[$i]}" >> "$CONFIG_FILE"
    ((i++)) || true
done

chmod 600 "$CONFIG_FILE"

echo ""
echo "✅ Configuration saved: $CONFIG_FILE"
echo ""
echo "🚀 Now you can use:"
echo "   ./local/dns-add.sh subdomain.yourdomain.com SERVER_IP"
echo ""
echo "   Example:"
echo "   ./local/dns-add.sh status.mycompany.com 185.181.10.50"
echo ""
