#!/bin/bash

# StackPilot - MinIO (S3-Compatible Object Storage)
# Self-hosted S3-compatible storage for files, backups, and media.
# https://min.io/
# Author: Paweł (Lazy Engineer)
#
# IMAGE_SIZE_MB=300  # minio/minio:latest ~300MB
#
# MinIO can be used as storage for:
# - Cap (video recordings)
# - Typebot (user-uploaded files)
# - Any application requiring S3

set -e

APP_NAME="minio"
STACK_DIR="/opt/stacks/$APP_NAME"
API_PORT=${PORT:-9000}
CONSOLE_PORT=${CONSOLE_PORT:-9001}

echo "--- 📦 MinIO Setup (S3-Compatible Storage) ---"
echo "MinIO is a self-hosted storage compatible with Amazon S3."
echo ""

# Generate random credentials if not provided
if [ -z "$MINIO_ROOT_USER" ]; then
    MINIO_ROOT_USER="admin"
fi

if [ -z "$MINIO_ROOT_PASSWORD" ]; then
    MINIO_ROOT_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
    echo "🔐 Root password generated: $MINIO_ROOT_PASSWORD"
fi

# Optional: default bucket
DEFAULT_BUCKET=${DEFAULT_BUCKET:-}

echo "✅ Configuration:"
echo "   API Port: $API_PORT (S3 endpoint)"
echo "   Console Port: $CONSOLE_PORT (Web UI)"
echo "   Root User: $MINIO_ROOT_USER"
if [ -n "$DEFAULT_BUCKET" ]; then
    echo "   Default Bucket: $DEFAULT_BUCKET"
fi
echo ""

# Prepare directory
sudo mkdir -p "$STACK_DIR"
cd "$STACK_DIR"

# Create docker-compose.yaml
echo "--- Creating Docker configuration ---"

cat <<EOF | sudo tee docker-compose.yaml > /dev/null

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "${API_PORT}:9000"
      - "${CONSOLE_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

EOF

echo "--- Starting MinIO ---"
sudo docker compose up -d

# Health check
source /opt/stackpilot/lib/health-check.sh 2>/dev/null || true
if type wait_for_healthy &>/dev/null; then
    wait_for_healthy "$APP_NAME" "$API_PORT" 60 || { echo "❌ Installation failed!"; exit 1; }
else
    sleep 5
    if sudo docker compose ps --format json | grep -q '"State":"running"'; then
        echo "✅ MinIO is running"
    else
        echo "❌ Container failed to start!"; sudo docker compose logs --tail 20; exit 1
    fi
fi

# Create default bucket if specified
if [ -n "$DEFAULT_BUCKET" ]; then
    echo ""
    echo "--- Creating bucket: $DEFAULT_BUCKET ---"
    sleep 3  # Wait for MinIO to fully start

    # Use mc inside the container (available since MinIO RELEASE.2023-03-20)
    # Alternatively: curl to API
    if sudo docker exec minio mc alias set local http://localhost:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" 2>/dev/null; then
        if sudo docker exec minio mc mb local/"$DEFAULT_BUCKET" 2>/dev/null; then
            echo "✅ Bucket '$DEFAULT_BUCKET' created"
        else
            echo "⚠️  Bucket may already exist or an error occurred"
        fi
    else
        echo "⚠️  mc client unavailable - bucket will be created on first use"
    fi
fi

# Save credentials to file
echo ""
echo "💾 Saving credentials to $STACK_DIR/.env..."
cat <<EOF | sudo tee "$STACK_DIR/.env" > /dev/null
# MinIO Credentials
# Generated by install.sh - DO NOT DELETE!
MINIO_ROOT_USER=$MINIO_ROOT_USER
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
MINIO_ENDPOINT=http://localhost:$API_PORT
EOF
sudo chmod 600 "$STACK_DIR/.env"

# HTTPS configuration
if [ -n "$DOMAIN" ] && [ "$DOMAIN" != "-" ]; then
    echo ""
    echo "--- Configuring HTTPS via Caddy ---"
    if command -v sp-expose &> /dev/null; then
        # Expose Console (Web UI)
        sudo sp-expose "$DOMAIN" "$CONSOLE_PORT"
        echo "✅ Console available at https://$DOMAIN"

        # Info about API endpoint
        echo ""
        echo "⚠️  S3 API (port $API_PORT) requires separate configuration:"
        echo "   For external access to S3 API use a subdomain, e.g.:"
        echo "   s3.$DOMAIN -> localhost:$API_PORT"
    else
        echo "⚠️  'sp-expose' not found. Install Caddy: system/caddy-install.sh"
    fi
fi

echo ""
echo "============================================"
echo "✅ MinIO installed!"
echo ""
echo "📋 Access:"
if [ -n "$DOMAIN" ] && [ "$DOMAIN" != "-" ]; then
    echo "   Console (Web UI): https://$DOMAIN"
    echo "   S3 API: http://localhost:$API_PORT (local)"
elif [ "$DOMAIN" = "-" ]; then
    echo "   Domain will be configured automatically after installation"
else
    echo "   Console (Web UI): http://localhost:$CONSOLE_PORT"
    echo "   S3 API: http://localhost:$API_PORT"
fi
echo ""
echo "🔐 Credentials:"
echo "   User: $MINIO_ROOT_USER"
echo "   Password: $MINIO_ROOT_PASSWORD"
echo ""
echo "📝 Usage with other applications:"
echo "   S3_ENDPOINT=http://minio:9000"
echo "   S3_ACCESS_KEY=$MINIO_ROOT_USER"
echo "   S3_SECRET_KEY=$MINIO_ROOT_PASSWORD"
echo "   S3_BUCKET=<bucket-name>"
echo ""
echo "💡 Creating a bucket via CLI:"
echo "   docker exec minio mc alias set local http://localhost:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD"
echo "   docker exec minio mc mb local/bucket-name"
echo "============================================"
